# Generated by Django 4.1.3 on 2022-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
    ]
